name: Fetch News
on:
  schedule:
    - cron: '0 */2 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        # Notice we added cloudscraper here!
        run: pip install requests beautifulsoup4 lxml cloudscraper
        
      - name: Run scraper
        run: python scraper.py
        
      - name: Save HTML to repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html articles/
          git commit -m "Update news pages" || exit 0
          git push
